### ISSUE TITLE
add pester and PS Script Analyzer to new Powershell script

### ISSUE THREAD

**Issue by rshade** [rs-services/server-templates#28]
https://github.com/PowerShell/PSScriptAnalyzer#linux-tested-only-on-ubuntu-1404
https://gist.github.com/ishu3101/92d43aac6f1bcc6e3e6b072961e7d6d4

**Comment by dfrankel33** [comment]
Per https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md : 

> Substantial changes were required, to get Pester executing on non-Windows systems. These changes are not yet in the official Pester code base. Some features of Pester may not be available or may have incorrect behavior.

**Comment by rshade** [comment]
Completed
