### ISSUE TITLE
Unexpected behavior on Chef Server ST with `CHEF_SERVER_ADDONS` input

### ISSUE THREAD

**Issue by bryankaraffa** [rs-services/server-templates#38]
With rev14 of the published Chef ServerTemplate we are having some odd issues

CHEF_SERVER_ADDONS

- ((CHEF_SERVER_ADDONS==array["text:manage"]   OR
CHEF_SERVER_ADDONS==array["text:manage", "text:reporting"] )) AND CHEF_VERSION==12.12.0
  - 502 Gateway error when attempting to access Manage UI.
  - this behavior is only affect when using default CHEF_VERSION [12.12.0].  using CHEF_VERSION=12.14.0 [latest stable] works as expected.

- CHEF_SERVER_ADDONS == array[""] 
  - instance goes stranded -- cannot get boot bundle 
  - this has been Escalated to RS Engineering as a bug https://bookiee.rightscale.com/browse/CM-2709
  - Example: https://us-3.rightscale.com/acct/7954/servers/1499514003?instance_id=218593631003#audit_entries

Expectation is that we can install just the manage addon, without reporting, if desired.  While we weren't able to test this with 0 addons enabled because of the CM bug discovered, same expectation would be that this would go operational with 0 addons installed after it has gone operational.

Original ZD Ticket: #125047

**Comment by stefhen** [comment]
This was fixed / removed in https://github.com/rs-services/server-templates/pull/57

Passing an empty array as mentioned will cause the launch to hang. Also you have to provide a hash to the chef recipe if you want to pin a specific version of an addon, which is needed with older Chef releases or the launch will hang. Passing a real hash object isn't really doable, and none of our customers currently use these addons by default. I've just removed this input, and if someone wants to use an addon after installing they can just do `chef-server-ctl install <addon>`.
